# Import the State definition.
# searchState defines the structure of the data that flows
# through our LangGraph.
from langgraph_fundamentals.prompt_chaining.state import searchState


# Import the LLM that will be used to generate the responses.
from Models.openAI_llm import llm


# StrOutputParser converts the LLM's response into a simple string.
from langchain_core.output_parsers import StrOutputParser


# PromptTemplate is used to create reusable prompts
# with dynamic variables such as {topic}, {state}, and {outline}.
from langchain_core.prompts import PromptTemplate


# Create an output parser.
#
# The LLM may return an AIMessage object.
# StrOutputParser extracts the actual text from that response.
parser = StrOutputParser()


# =========================================================
# SEARCH DETAILS PROMPT
# =========================================================

# This prompt is responsible for generating the COMPLETE
# details of the topic.
#
# It receives three pieces of information:
#
# 1. topic   -> The topic provided by the user
# 2. outline -> The outline generated by the previous node
# 3. state   -> The complete current state of the graph
#
search_details_prompt = PromptTemplate(
    template="""
        Provide the full details from the topic: {topic}

        This is the outline for the generation:
        {outline}

        This is the full state of the object:
        {state}
    """,

    # These are the variables that must be provided
    # when this prompt is invoked.
    input_variables=["state", "topic", "outline"]
)


# =========================================================
# SEARCH OUTLINE PROMPT
# =========================================================

# This prompt is responsible for creating an OUTLINE
# for the topic provided by the user.
#
# At this stage, we only have the topic and the current state.
#
search_outline_prompt = PromptTemplate(
    template="""
        Create an outline for the topic: {topic}

        This is the full state of the object:
        {state}
    """,

    # Variables required by this prompt.
    input_variables=["state", "topic"]
)


# =========================================================
# SEARCH DETAILS NODE
# =========================================================

# This function represents one NODE in our LangGraph.
#
# Input:
#     state -> Current state of the graph
#
# Output:
#     searchState -> Updated state containing the description
#
def search_details(state: searchState) -> searchState:

    # Create a LangChain chain using the pipe operator.
    #
    # Flow:
    #
    # PromptTemplate
    #       ↓
    #      LLM
    #       ↓
    # StrOutputParser
    #
    chain_search_details = search_details_prompt | llm | parser


    # Execute the chain.
    #
    # We provide the values required by the prompt.
    result = chain_search_details.invoke({

        # Pass the complete current state.
        "state": state,

        # Extract the topic from the state.
        "topic": state["topic"],

        # Extract the outline generated by the
        # search_outline node.
        "outline": state["outline"]
    })


    # Return the UPDATED state.
    #
    # **state means:
    # "Keep all the existing values in the state."
    #
    # Then we add/update the "desciption" field.
    return {
        **state,
        "desciption": result
    }


# =========================================================
# SEARCH OUTLINE NODE
# =========================================================

# This function represents the first processing node
# in our LangGraph.
#
# Input:
#     state -> Current graph state
#
# Output:
#     searchState -> Updated state containing the outline
#
def search_outline(state: searchState) -> searchState:

    # Create the chain:
    #
    # Prompt
    #   ↓
    # LLM
    #   ↓
    # Parser
    #
    chain_search_outline = search_outline_prompt | llm | parser


    # Execute the chain with the required input values.
    result = chain_search_outline.invoke({

        # Pass the complete state to the prompt.
        "state": state,

        # Extract the topic from the state.
        "topic": state["topic"]
    })


    # Return the updated state.
    #
    # **state keeps all existing state values.
    #
    # "outline": result adds the newly generated outline.
    return {
        **state,
        "outline": result
    }