# TypedDict allows us to define the structure/schema
# of a Python dictionary.
#
# In LangGraph, TypedDict is commonly used to define
# the State of the graph.

from typing import TypedDict


# =========================================================
# SEARCH STATE
# =========================================================

# searchState defines what data can exist inside
# the state object of our LangGraph.
#
# Every node receives this state and can return
# an updated version of this state.
class searchState(TypedDict):

    # The topic provided by the user.
    #
    # Example:
    # "LangGraph"
    topic: str


    # The outline generated by the search_outline node.
    #
    # Example:
    # "1. What is LangGraph?
    #  2. State
    #  3. Nodes
    #  4. Edges"
    outline: str


    # The detailed explanation generated by
    # the search_details node.
    #
    # Example:
    # "LangGraph is a framework for building..."
    desciption: str