# Import TypedDict from Python's typing module.
#
# TypedDict is used to define the structure/shape of a dictionary.
# It helps us specify:
#   - What keys the state should contain
#   - What type of value each key should store
#
# In LangGraph, this TypedDict will be used as the
# state schema for our graph.
from typing import TypedDict


# Define the state structure for the BMI LangGraph.
#
# BMIState represents the shared state/data that flows
# from one node to another in the graph.
#
# Each node can read values from this state and return
# an updated state with additional or modified values.
class BMIState:

    # User's weight in kilograms.
    #
    # Example:
    #     weight = 70.5
    weight: float


    # User's height in meters.
    #
    # Example:
    #     height = 1.75
    height: float


    # Calculated Body Mass Index (BMI).
    #
    # This value is calculated by the calculate_BMI node.
    #
    # Formula:
    #     BMI = weight / (height * height)
    #
    # Example:
    #     BMI = 22.86
    BMI: float


    # Suggestions generated based on the calculated BMI.
    #
    # This value is generated by the BMI_suggestion node,
    # which uses the LLM to provide health-related suggestions.
    #
    # Example:
    #     BMI_suggestion = "Maintain a balanced diet..."
    BMI_suggestion: str